# Site settings
title: Soma Recording Studios
email: somarecordingstudios@gmail.com
url: "http://zackhanni.github.io" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Located in the historic Fishtown district of Philadelphia, Soma Recording Studios was founded by producer, and mixing and mastering engineer Zack Hanni in 2007.
  We pride ourselves on having a relaxed, laid-back atmosphere, with the commitment, equipment, and quality of a major recording studio.
  Our competitive rates and ability to exceed expectations have kept our clients coming back, time and time again.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: somaaamusic
github_username:  zackhanni

# Footer settings
footer: Soma Recording Studios

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/somaaamusic
  - title: thumbtack
    url: https://www.thumbtack.com/profile/services/2PD0eXy78jLD6A
  - title: youtube
    url: https://www.youtube.com/user/basscreators

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - octopress-debugger
